version: '3'
services:
  nextjs:
    build: .
    container_name: "Nextjs_frontend"
    environment:
      - TZ=Asia/Taipei
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
    working_dir : /var/www
    command: bash "setEnv.sh"
    